# Generated by Django 5.1.5 on 2025-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
